// import { createClient } from "@/lib/supabase/server"
// import { v4 as uuidv4 } from "uuid"

// export async function POST(req: Request) {
//   try {
//     const supabase = await createClient()
//     const {
//       data: { user },
//     } = await supabase.auth.getUser()

//     if (!user) {
//       return Response.json({ error: "Unauthorized" }, { status: 401 })
//     }

//     const { name, description, platforms, startDate, endDate, postTime, products, scheduleType } = await req.json()

//     if (!name || !platforms?.length || !products?.length) {
//       return Response.json({ error: "Missing required fields" }, { status: 400 })
//     }

//     const campaignId = uuidv4()
//     const start = new Date(startDate)
//     const end = new Date(endDate)

//     const { error: campaignError } = await supabase.from("campaigns").insert({
//       id: campaignId,
//       user_id: user.id,
//       name,
//       description,
//       platforms,
//       status: "scheduled",
//       start_date: start.toISOString(),
//       end_date: end.toISOString(),
//       post_time: postTime,
//       schedule_type: scheduleType,
//       total_posts: products.length,
//     })

//     if (campaignError) {
//       return Response.json({ error: "Failed to create campaign" }, { status: 500 })
//     }

//     const daysDiff = Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24))
//     const productsPerDay = Math.ceil(products.length / daysDiff)

//     let postCount = 0

//     for (let i = 0; i < products.length; i++) {
//       const dayOffset = Math.floor(i / productsPerDay)
//       const scheduledDate = new Date(start)
//       scheduledDate.setDate(scheduledDate.getDate() + dayOffset)
//       const [hours, minutes] = postTime.split(":").map(Number)
//       scheduledDate.setHours(hours, minutes, 0, 0)

//       // Create scheduled post for each platform
//       for (const platform of platforms) {
//         const { error: postError } = await supabase.from("scheduled_posts").insert({
//           id: uuidv4(),
//           user_id: user.id,
//           product_id: products[i],
//           campaign_id: campaignId,
//           platform,
//           content: "", // Will be generated by AI
//           scheduled_date: scheduledDate.toISOString(),
//           status: "scheduled",
//         })

//         if (!postError) {
//           postCount++
//         }
//       }
//     }

//     // Update total posts count
//     await supabase.from("campaigns").update({ total_posts: postCount }).eq("id", campaignId)

//     return Response.json({
//       success: true,
//       campaignId,
//       totalScheduledPosts: postCount,
//     })
//   } catch (error) {
//     console.error("[v0] Campaign creation error:", error)
//     return Response.json(
//       {
//         error: "Failed to create campaign",
//         details: error instanceof Error ? error.message : "Unknown error",
//       },
//       { status: 500 },
//     )
//   }
// }

















import { createClient } from "@/lib/supabase/server"
import { v4 as uuidv4 } from "uuid"

export async function POST(req: Request) {
  console.log("🔵 Campaign creation request received")
  
  try {
    const supabase = await createClient()
    const {
      data: { user },
      error: authError
    } = await supabase.auth.getUser()

    if (authError) {
      console.error("❌ Auth error:", authError)
      return Response.json({ error: "Authentication error" }, { status: 401 })
    }

    if (!user) {
      console.error("❌ No user found")
      return Response.json({ error: "Unauthorized" }, { status: 401 })
    }

    console.log("✅ User authenticated:", user.id)

    const body = await req.json()
    console.log("📦 Request body:", JSON.stringify(body, null, 2))

    const { name, description, platforms, startDate, endDate, postTime, products, scheduleType } = body

    // Enhanced validation
    if (!name?.trim()) {
      console.error("❌ Missing campaign name")
      return Response.json({ error: "Campaign name is required" }, { status: 400 })
    }

    if (!platforms?.length) {
      console.error("❌ No platforms selected")
      return Response.json({ error: "Please select at least one platform" }, { status: 400 })
    }

    if (!products?.length) {
      console.error("❌ No products selected")
      return Response.json({ error: "Please select at least one product" }, { status: 400 })
    }

    if (!startDate || !endDate) {
      console.error("❌ Missing date information")
      return Response.json({ error: "Start and end dates are required" }, { status: 400 })
    }

    console.log("✅ All validations passed")

    const campaignId = uuidv4()
    const start = new Date(startDate)
    const end = new Date(endDate)

    // Validate dates
    if (start >= end) {
      console.error("❌ Invalid date range")
      return Response.json({ error: "End date must be after start date" }, { status: 400 })
    }

    console.log("📅 Date range:", start.toISOString(), "to", end.toISOString())

    // Create campaign
    const campaignData = {
      id: campaignId,
      user_id: user.id,
      name: name.trim(),
      description: description?.trim() || "",
      platforms,
      status: "scheduled",
      start_date: start.toISOString(),
      end_date: end.toISOString(),
      post_time: postTime || "09:00",
      schedule_type: scheduleType || "daily",
      total_posts: 0, // Will be updated after posts are created
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }

    console.log("🎯 Inserting campaign:", campaignData)

    const { data: campaign, error: campaignError } = await supabase
      .from("campaigns")
      .insert(campaignData)
      .select()
      .single()

    if (campaignError) {
      console.error("❌ Campaign creation error:", campaignError)
      return Response.json({ 
        error: "Failed to create campaign", 
        details: campaignError.message 
      }, { status: 500 })
    }

    console.log("✅ Campaign created:", campaignId)

    // Calculate schedule
    const daysDiff = Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24))
    const productsPerDay = Math.max(1, Math.ceil(products.length / Math.max(1, daysDiff)))

    console.log(`📊 Scheduling ${products.length} products over ${daysDiff} days (${productsPerDay} per day)`)

    let postCount = 0
    const scheduledPosts = []

    // Create scheduled posts
    for (let i = 0; i < products.length; i++) {
      const dayOffset = Math.floor(i / productsPerDay)
      const scheduledDate = new Date(start)
      scheduledDate.setDate(scheduledDate.getDate() + dayOffset)
      
      const [hours, minutes] = (postTime || "09:00").split(":").map(Number)
      scheduledDate.setHours(hours, minutes, 0, 0)

      // Create scheduled post for each platform
      for (const platform of platforms) {
        const postId = uuidv4()
        const postData = {
          id: postId,
          user_id: user.id,
          product_id: products[i],
          campaign_id: campaignId,
          platform,
          content: "", // Will be generated by AI
          scheduled_date: scheduledDate.toISOString(),
          status: "scheduled",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }

        scheduledPosts.push(postData)
        postCount++
      }
    }

    console.log(`📝 Creating ${scheduledPosts.length} scheduled posts`)

    // Batch insert all scheduled posts
    if (scheduledPosts.length > 0) {
      const { error: postsError } = await supabase
        .from("scheduled_posts")
        .insert(scheduledPosts)

      if (postsError) {
        console.error("❌ Scheduled posts creation error:", postsError)
        
        // Clean up: delete the campaign if posts failed
        await supabase.from("campaigns").delete().eq("id", campaignId)
        
        return Response.json({ 
          error: "Failed to create scheduled posts",
          details: postsError.message
        }, { status: 500 })
      }
    }

    // Update total posts count
    const { error: updateError } = await supabase
      .from("campaigns")
      .update({ total_posts: postCount })
      .eq("id", campaignId)

    if (updateError) {
      console.error("❌ Failed to update post count:", updateError)
    }

    console.log("🎉 Campaign creation completed successfully!")
    console.log(`📊 Created ${postCount} scheduled posts for campaign ${campaignId}`)

    return Response.json({
      success: true,
      campaignId,
      totalScheduledPosts: postCount,
      message: "Campaign created successfully"
    })

  } catch (error) {
    console.error("💥 Unexpected error in campaign creation:", error)
    return Response.json(
      {
        error: "Failed to create campaign",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}