// lib/docs/data.ts
// Central content for documentation pages.
// Keep copy, lists, and workflow steps here so the page code stays clean.

export const FEATURES = [
  {
    id: "dashboard",
    title: "Unified Dashboard",
    short: "One place to manage all connected social accounts, schedules, and analytics.",
    details:
      "A single dashboard lists connected social accounts, upcoming scheduled posts, quick actions (create campaign, bulk upload), and health metrics — engagement, reach, and posting consistency.",
    icon: "📊",
  },
  {
    id: "content-calendar",
    title: "10-Day Content Calendar",
    short: "Create, preview and schedule a 10-day posting plan quickly.",
    details:
      "Interactive calendar with day-by-day post previews. Create a campaign with 10 post slots — upload images, product names, and minimal details; RankU handles SEO, content generation and scheduling.",
    icon: "📅",
  },
  {
    id: "ai-research",
    title: "AI Research Agent",
    short: "Automated product research to generate SEO-rich descriptions and keywords.",
    details:
      "When a product is submitted, the Research Agent gathers competitor info, finds high-performing keywords/hashtags, and prepares platform-specific copy (Facebook, Instagram, Website meta).",
    icon: "🤖",
  },
  {
    id: "auto-posting",
    title: "Auto-Posting Agent",
    short: "Schedule-based automated posting using connected user accounts.",
    details:
      "Auto Post Agent posts the generated content to the user's connected social accounts on schedule. Supports re-try on failed posts and logs status for each task.",
    icon: "🚀",
  },
  {
    id: "social-connect",
    title: "Social Account Connectors",
    short: "Secure OAuth flows to connect Facebook, Instagram, LinkedIn, and X.",
    details:
      "Connect multiple accounts per platform, manage tokens securely via Supabase (or any secret store), and provide granular permissions for posting & analytics.",
    icon: "🔗",
  },
  {
    id: "analytics",
    title: "Analytics & Insights",
    short: "Performance metrics & suggestions to improve reach and engagement.",
    details:
      "Weekly summaries, per-post engagement, best-time suggestions, and actionable tips generated by the Analytics Agent based on real performance data.",
    icon: "📈",
  },
]

export const WORKFLOW_STEPS = [
  {
    id: "signup",
    title: "Sign Up / Onboard",
    summary: "User registers and verifies account to access the dashboard.",
    details:
      "Users sign up via Supabase/Clerk and complete a quick onboarding: link social accounts and choose preferred platforms. Minimal profile required.",
  },
  {
    id: "create-campaign",
    title: "Create Campaign",
    summary: "User creates a 10-day campaign and uploads products/images.",
    details:
      "User supplies product image, name, short details; chooses which platforms to post to and schedule preferences (time windows).",
  },
  {
    id: "research-agent",
    title: "Research Agent",
    summary: "AI analyzes product & generates SEO-rich assets.",
    details:
      "Agent performs competitor scan, keyword extraction, and writes platform-tailored descriptions, hashtags and CTA variants.",
  },
  {
    id: "review",
    title: "Review & Approve",
    summary: "User reviews AI-generated content and makes edits if needed.",
    details:
      "A quick review interface lets users accept auto-filled text, modify copy, swap images and reorder scheduled slots.",
  },
  {
    id: "posting-agent",
    title: "Auto Post Agent",
    summary: "Scheduled posts are published automatically through connected accounts.",
    details:
      "Agent posts to each platform at scheduled times, handles failures (retries), and records results to the dashboard activity log.",
  },
  {
    id: "analytics",
    title: "Monitor & Optimize",
    summary: "Analytics agent collects post-performance and recommends improvements.",
    details:
      "Weekly reports and AI suggestions (better times, hashtag changes) that can be applied to future campaigns automatically.",
  },
]

export const PARTNER_GUIDE = {
  overview:
    "RankU partners (marketing agencies, resellers, affiliates) can use the platform to manage client accounts, scale content generation, and offer automated posting as a service. Partners get access to white-label features, bulk upload tools, and agency-level analytics.",
  steps: [
    {
      title: "Sign Up as a Partner",
      desc: "Register for a partner account and complete verification. Partners receive dashboard tools for client management and billing.",
    },
    {
      title: "Onboard Clients",
      desc: "Invite clients via email to link their social accounts. Manage multiple client workspaces from a single partner dashboard.",
    },
    {
      title: "Run Bulk Campaigns",
      desc: "Use the bulk upload feature for large catalogs. Schedule multi-client campaigns and let the AI generate platform-specific content.",
    },
    {
      title: "White-label & Resell",
      desc: "Use white-labeling options to present RankU as your firm's solution. Charge clients monthly for managed services.",
    },
    {
      title: "Revenue & Billing",
      desc: "Partners can use our billing API or export usage reports to invoice clients. For white-label, contact sales for custom SLA and pricing.",
    },
  ],
}
